name: flutter_raytracing
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.13.0-0 <3.0.0"

dependencies:
  image: ^3.0.2
  vector_math:

dev_dependencies:
  extra_pedantic: ^1.4.0
